{% set name = "patch-ng" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da067628d6d5fd9dc5a55eab37951d46bd95661b7219fab364b711366abcc690

build:
  noarch: python
  number: 1
  entry_points:
    - patch-ng = patch_ng:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - patch-ng --help

about:
  home: https://github.com/conan-io/python-patch-ng
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to parse and apply unified diffs

extra:
  recipe-maintainers:
    - abloemert
